- name: main
  elements: [gallery, testimonial]


- name: coachings
  elements: [gallery, testimonial]
- name: trainings
  elements: [gallery, testimonial]
- name: orgdev
  elements: [gallery, testimonial]
- name: contact
  elements: []
