- name: coachings
  elements: [title, image, testimonial, description, contact_form]
- name: trainings
  elements: [title, image, testimonial, description, contact_form]
- name: orgdev
  elements: [title, image, testimonial, description, contact_form]
- name: contact
  elements: []
