# == In this configuration you setup Alchemy´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: image
  picture_gallery: true

- name: testimonial
  contents:
    - name: quote
      type: EssenceText
      validate:
        - presence
    - name: logo
      type: EssencePicture
      validate:
        - presence
