# == In this configuration you setup Alchemy´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: gallery
  picture_gallery: true
  
- name: testimonial
  contents:
    - name: company
      type: EssenceText
      validate: [presence]
    - name: quote
      type: EssenceText
      validate:
        - presence
    - name: logo
      type: EssencePicture
      validate:
        - presence
