# == In this configuration you setup Alchemy´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: logo
  contents:
    - name: image
      type: EssencePicture
      validate: [presence]

- name: logo_text
  contents:
  - name: logo_text
    type: EssenceHtml
    validate: [presence]

- name: title
  contents:
    - name: title
      type: EssenceText
      validate: [presence]

- name: testimonial
  contents:
    - name: company
      type: EssenceText
      validate: [presence]
    - name: quote
      type: EssenceText
      validate:
        - presence
    - name: logo
      type: EssencePicture
      validate:
        - presence

- name: contact_form
  contents:
  - name: mail_from
    type: EssenceText
    validate:
    - presence
    - format: email
  - name: mail_to
    type: EssenceText
    validate:
    - presence
    - format: email
  - name: subject
    type: EssenceText
    validate:
    - presence
  - name: success_page
    type: EssenceSelect
    validate:
    - presence

- name: description
  contents:
    - name: description
      type: EssenceRichtext
