# == In this configuration you setup Alchemy´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: logo
  contents:
    - name: image
      type: EssencePicture
      validate:
        - presence: true
    - name: logo_text
      type: EssenceHtml
      validate:
        - presence: true

- name: offer
  contents:
    - name: nav_image
      type: EssencePicture
      validate:
        - presence: true
    - name: section
      type: EssenceText
      validate:
        - presence: true
    - name: title
      type: EssenceText
      validate:
        - presence: true
    - name: teaser
      type: EssenceRichtext
      validate:
        - presence: true
    - name: description
      type: EssenceRichtext

- name: topics
  contents:
    - name: title
      type: EssenceText
      validate:
      - presence: true
  available_contents:
    - name: topic
      type: EssenceText

- name: testimonial
  contents:
    - name: company
      type: EssenceText
      validate:
        - presence: true
    - name: quote
      type: EssenceText
      validate:
        - presence: true
    - name: logo
      type: EssencePicture
      validate:
        - presence: true

- name: contact_form
  contents:
    - name: mail_from
      type: EssenceText
      validate:
        - presence: true
        - format: email
    - name: mail_to
      type: EssenceText
      validate:
        - presence: true
        - format: email
    - name: subject
      type: EssenceText
      validate:
        - presence: true
    - name: success_page
      type: EssenceSelect
      validate:
        - presence: true

- name: static_page
  contents:
    - name: title
      type: EssenceText
    - name: body
      type: EssenceRichtext

