# == This file defines the page layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: home
  unique: true
  elements: [teaser, quote]

- name: static
  elements:
    - static_page
  autogenerate:
    - static_page

- name: header
  layoutpage: true
  unique: true
  elements: [logo, logo_text]
  autogenerate: [logo, logo_text]

- name: footer
  layoutpage: true
  unique: true
  elements: [address, link, contact_form]

