# == This file defines the page layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: home
  unique: true
  cells: [main, coachings, trainings, orgdev, contact]
  elements: [title, gallery, testimonial, description, contact_form]
