# == This file defines the page layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: home
  unique: true
  cells: [main, coachings, trainings, orgdev, contact]
  elements: [nav_image, title, gallery, testimonial, teaser, description, contact_form]

- name: header
  layoutpage: true
  unique: true
  elements: [logo, logo_text]
  autogenerate: [logo, logo_text]
